version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["6c:a6:69:3f:7e:ab:11:df:01:55:61:c4:fe:43:1c:d7"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apt add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # test if the website exists
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi
# Sequential workflow
# run code again
workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      # - configure_infrastructure
      - smoke_test
